apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards
  labels:
    app: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
        - name: cards
          image: centralbank/cards-microservice:s1
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://configserver:8071/"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eurekaserver:8072/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: cards
spec:
  selector:
    app: cards
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP