apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver
  labels:
    app: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
        - name: gatewayserver
          image: centralbank/gateway-microservice:s1
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://configserver:8071/"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eurekaserver:8072/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayserver
spec:
  selector:
    app: gatewayserver
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort