apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans
  labels:
    app: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
        - name: loans
          image: centralbank/loans-microservice:s1
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://configserver:8071/"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eurekaserver:8072/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: loans
spec:
  selector:
    app: loans
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP