apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: centralbank/accounts-microservice:s1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://configserver:8071/"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eurekaserver:8072/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP